project_id = "mubuncckmiyxxnlxnecn"

[functions.google-maps-geocode]
verify_jwt = true

[functions.emergency-alert]
verify_jwt = false

[functions.export-data]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.reset-counters]
verify_jwt = false

[functions.service-crew-notify]
verify_jwt = false

[functions.telegram-notify]
verify_jwt = false

[functions.telegram-readiness-callback]
verify_jwt = false

[functions.clear-readiness-alert]
verify_jwt = true

[functions.telegram-setup]
verify_jwt = false

[functions.telegram-webhook-setup]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.auto-close-old-alerts]
verify_jwt = false